# Generated by Django 6.0.5 on 2026-07-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0003_service_businesshours"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=255)),
                ("image_url", models.URLField(max_length=500)),
                ("alt_text", models.CharField(blank=True, max_length=150)),
                ("is_cover", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de negocio",
                "verbose_name_plural": "Imágenes de negocio",
                "ordering": ["business", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_cover", True)),
                        fields=("business",),
                        name="one_cover_per_business",
                    )
                ],
            },
        ),
    ]
