# Generated by Django 6.0.5 on 2026-07-01 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0003_service_businesshours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "price_at_booking",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("duration_at_booking", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("cancelled", "Cancelada"),
                            ("completed", "Completada"),
                            ("no_show", "No asistió"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("marketplace", "Marketplace"), ("direct", "Directa")],
                        default="marketplace",
                        max_length=20,
                    ),
                ),
                ("is_first_booking_for_business", models.BooleanField(default=False)),
                ("customer_note", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="businesses.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-start_datetime"],
                "indexes": [
                    models.Index(
                        fields=["business", "start_datetime"],
                        name="bookings_bo_busines_814c5a_idx",
                    ),
                    models.Index(
                        fields=["customer", "status"],
                        name="bookings_bo_custome_0cbf77_idx",
                    ),
                    models.Index(
                        fields=["status"], name="bookings_bo_status_233e96_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_datetime__gt", models.F("start_datetime"))
                        ),
                        name="booking_end_after_start",
                    )
                ],
            },
        ),
    ]
