# Generated by Django 6.0.5 on 2026-07-29 20:13

import bookings.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_review_reviewresponse_and_more"),
        ("businesses", "0005_normalize_businesshours_granularity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed"])),
                expressions=(
                    (
                        bookings.models.TsTzRange(
                            "start_datetime",
                            "end_datetime",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    ("business", "="),
                ),
                name="excluir_reservas_solapadas",
            ),
        ),
    ]
