# Generated by Django 6.0.5 on 2026-09-22 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking_excluir_reservas_solapadas"),
        ("businesses", "0005_normalize_businesshours_granularity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("customer__isnull", False), ("guest_name", "")),
                    models.Q(
                        ("customer__isnull", True),
                        models.Q(("guest_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="booking_customer_xor_guest",
            ),
        ),
    ]
