# Generated by Django 6.0.5 on 2026-09-22 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_customer_nullable_and_guest"),
        ("businesses", "0005_normalize_businesshours_granularity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "start_datetime"],
                name="bookings_bo_status_f6e1f8_idx",
            ),
        ),
    ]
